apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-kotlin-app-monitor
spec:
  selector:
    matchLabels:
      app: spring-kotlin-app
  endpoints:
  - port: web
    path: /actuator/prometheus
    interval: 30s
